name: PtyLab
dependencies:
  - python=3.10
  - numpy
  - conda-forge::cupy
  - h5py
  - matplotlib
  - scipy
  - scikit-image
  - pyqtgraph
  - tqdm
  - pytables
  - matplotlib
  - numpy
  - h5py
  # optional
  - conda-forge::scikit-image
  - conda-forge::scikit-learn
  - conda-forge::tensorflow-cpu
  - napari
  #- conda-forge::tensorflow-cpu
  - pip
#  - pip:
#      tensorflow-cpu