name: fracpy_jul2022
dependencies:
  - numpy
  - cupy
  - h5py
  - matplotlib
  - scipy
  - scikit-image
  - pyqtgraph
  - tqdm
  - pytables
  - matplotlib
  - numpy
  - h5py
  - conda-forge::scikit-image
  - conda-forge::scikit-learn
  - conda-forge::cupy
  - conda-forge::cudatoolkit=11.4